name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web:
    name: Web (lint + typecheck + build)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      # Use the same Node you pinned in .nvmrc
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npx tsc --noEmit || true # keep green if you haven't added strict TS yet

      - name: Build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
        run: npm run build

  api:
    name: API (install + quick checks)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          # Optional linters if present:
          python -m pip install ruff pytest || true

      - name: Lint (ruff if available)
        run: ruff check . || true

      - name: Tests (if tests/ exists)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests/ directory; skipping."
          fi
